package computeclient;

import Contract.CFile;
import Contract.CSAuthenticator;
import Contract.Factorization;
import Contract.Fibonacci;
import Contract.PerfectNumber;
import Contract.Task;

import javax.crypto.SecretKey;
import javax.swing.*;
import java.io.*;
import java.awt.event.*;
import java.net.*;
import Security.SecurityUtil;
 import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.HashMap;


public class MainFrame extends JFrame {

    // Arrays to track the state of uploaded class files
    String[] task = {"Generate Fibonacci sequence", "Search perfect number", "Factorize Number"};
      String name   ;
    String[] classFiles = {"Fibonacci.class", "PerfectNumber.class", "Factorization.class"};
    ObjectOutputStream out = null;
    ObjectInputStream in = null;
    boolean[] uploaded = {false, false, false};
    // Socket for communication with the server
    private Socket socket;
    SecretKey sessionKey;

    /**
     * Constructor for the MainFrame class. Initializes UI components and sets
     * up event listeners.
     */
    public MainFrame() {
        initComponents();

        uploadButton.setEnabled(false);
        offloadButton.setEnabled(false);
        clearButton.setEnabled(false);
        taskListCombobox.setEnabled(false);
        clearButton.setEnabled(false);
        authButton.setEnabled(false);
        resultTxtArea.setLineWrap(true);
        this.setTitle("Remote Task Offloading Framework");
        uploadButton.addActionListener(new UploadListener());
        offloadButton.addActionListener(new OffloadTaskListener());

        taskListCombobox.setModel(new DefaultComboBoxModel<>(task));

        clearButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                resultTxtArea.setText("");

            }
        });
    }

    /**
     * Method to set up a TCP connection with the server. Enables UI components
     * upon successful connection.
     */
    private void setConnection() {

        try {
            resultTxtArea.append("Attempting to connect to " + hostTxt.getText() + ":" + portTxt.getText() + " ...\n");
            socket = new Socket(hostTxt.getText(), Integer.parseInt(portTxt.getText()));
            if (socket.isConnected()) {
                  out = new ObjectOutputStream(socket.getOutputStream());
                  in = new ObjectInputStream(socket.getInputStream());
                
                    uploadButton.setEnabled(true);
                    offloadButton.setEnabled(false);
                    taskListCombobox.setEnabled(true);
                    clearButton.setEnabled(false);
                    authButton.setEnabled(true);

                    resultTxtArea.append("TCP Connection to the server is done! \n");
                
            } else {
                resultTxtArea.append("Server not ready \n");
            }

        } catch (NumberFormatException e) {
            resultTxtArea.append("Error: Invalid port number. Please enter a valid integer for the port.\n");
            System.err.println("Invalid port: " + e.getMessage());
        } catch (java.net.ConnectException e) {
            resultTxtArea.append("Error: Connection refused. Please ensure the server is running on " + 
                                 hostTxt.getText() + ":" + portTxt.getText() + "\n");
            System.err.println("Connection refused: " + e.getMessage());
        } catch (java.net.UnknownHostException e) {
            resultTxtArea.append("Error: Unknown host '" + hostTxt.getText() + "'. Please check the server address.\n");
            System.err.println("Unknown host: " + e.getMessage());
        } catch (Exception e) {
            resultTxtArea.append("Error connecting to the server: " + e.getMessage() + "\n");
            System.err.println("Connection error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        uploadButton = new javax.swing.JButton();
        offloadButton = new javax.swing.JButton();
        hostTxt = new javax.swing.JTextField();
        portTxt = new javax.swing.JTextField();
        taskListCombobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTxtArea = new javax.swing.JTextArea();
        authButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Server Host");

        jLabel2.setText("Task List");

        jLabel3.setText("Server Port");

        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Board");

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        offloadButton.setText("Offload Task");

        hostTxt.setText("localhost");

        portTxt.setText("6789");

        taskListCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Results Board");

        resultTxtArea.setColumns(20);
        resultTxtArea.setRows(5);
        jScrollPane1.setViewportView(resultTxtArea);

        authButton.setText("Authenticate");
        authButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("User Name");

        userNameTF.setText("Stephen Smith");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(setButton)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(23, 23, 23)
                                .addComponent(taskListCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uploadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(16, 16, 16)
                                        .addComponent(offloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(146, 146, 146))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(hostTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(portTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(setButton)
                            .addComponent(authButton)))
                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(taskListCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadButton)
                            .addComponent(offloadButton))))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed

        setConnection();


    }//GEN-LAST:event_setButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed

        if (sessionKey == null) {
            resultTxtArea.append("Error: Session key is null. Authentication may have failed. Please authenticate first.\n");
            return;
        }

        int taskIndex = taskListCombobox.getSelectedIndex();
        String filePath = "./build/classes/Contract/" + classFiles[taskIndex];
        File file = new File(filePath);
        //uploadTaskClass(file);
        try {

             //read file into byte array
            BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file));
            try (DataInputStream dis = new DataInputStream(bis)) {
                // ObjectOutputStream  out = new ObjectOutputStream(socket.getOutputStream());
                byte[] btArr = new byte[(int) file.length()];
                dis.readFully(btArr, 0, btArr.length);
                CFile cfile = new CFile(file.getName(), btArr);
                //encrypt cfile object with session key before uploading

                Object  encrptCfile =   SecurityUtil.SymEncrypt(SecurityUtil.convertObjectToBytes(cfile), sessionKey);
                out.writeObject(encrptCfile);
            }

            //out.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());

        }


    }//GEN-LAST:event_uploadButtonActionPerformed

  

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
         resultTxtArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void authButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authButtonActionPerformed
        resultTxtArea.append("The mutual authentication is progressing \n");
 

       try {
           name = userNameTF.getText();
        ///read in the public key of server and user
           HashMap<String, Object> priKeyMap = SecurityUtil.ReadinKeys(name+"-pri.ser");
           HashMap<String, Object> pubMap = SecurityUtil.ReadinKeys(name+"-pub.ser");
           PrivateKey priKey = (PrivateKey) priKeyMap.get(name);
           PublicKey centrePub = (PublicKey) pubMap.get("CENTRE");
           
           if (priKey == null) {
               resultTxtArea.append("Error: Private key not found for user '" + name + "'\n");
               return;
           }
           if (centrePub == null) {
               resultTxtArea.append("Error: Centre public key not found in key file\n");
               return;
           }
           
           String veriString = SecurityUtil.RandomAlphaNumericString(128);
           //encrypt the name with the private key of user
           String cipherName = SecurityUtil.asyEncrypt(name, priKey);
            //encrypt the verification string with the public key of server
           String cipherVeri = SecurityUtil.asyEncrypt(veriString, centrePub);
            System.out.println("---------");


           resultTxtArea.append("The verification String in plain text:" + veriString + " \n");
           //create CSAuthenticator
           CSAuthenticator auth = new CSAuthenticator(name, cipherName, cipherVeri, null);

           resultTxtArea.append("The verification String in cipher text:" + cipherVeri + " \n");

            out.writeObject(auth);

             out.flush();

            resultTxtArea.append("  The CSAuthenticator has been sent to server  \n");

            CSAuthenticator auth2 = (CSAuthenticator) in.readObject();
            //receive the  CSAuthenticator from server and decrypt it   to get  the session key.
             sessionKey =  SecurityUtil.DecryptSessionKey(auth2.getSessionKey(),  priKey);
            String centrePlain = auth2.getPlainUserName();
           //server name  in cipher text
            String CentreNameCipher = auth2.getCipherUserName();
            //decrypt the verification string with the public key of server
            String centreName = SecurityUtil.asyDecrypt(CentreNameCipher, centrePub);

            //decrypt the verification string with the session key
            String veriString2 = (String)SecurityUtil.SymDecryptObj (auth2.getVerificationString(), sessionKey);
                       if(veriString.equals(veriString2)&&centrePlain.equals(centreName)){
                         System.out.println(SecurityUtil.keytoB64String(sessionKey));
                        resultTxtArea.append("  the session key in plain text:"+SecurityUtil.keytoB64String(sessionKey)+" \n");
                        resultTxtArea.append("  The session key in cipher text:"+auth2.getSessionKey()+" \n");
                        resultTxtArea.append("  The mutual authentication is done \n");
                        taskListCombobox.setModel(new DefaultComboBoxModel<>(task));
                        uploadButton.setEnabled(true);
                        offloadButton.setEnabled(true);
                        taskListCombobox.setEnabled(true);
                        clearButton.setEnabled(true);
                    }
                    else{
                        resultTxtArea.append("  The server not verified successfully \n");
                        resultTxtArea.append("  Debug - Verification String Match: " + veriString.equals(veriString2) + "\n");
                        resultTxtArea.append("  Debug - Centre Name Match: " + centrePlain.equals(centreName) + "\n");
                        resultTxtArea.append("  Client veriString: " + veriString + "\n");
                        resultTxtArea.append("  Server veriString: " + veriString2 + "\n");
                        resultTxtArea.append("  Client centreName: " + centreName + "\n");
                        resultTxtArea.append("  Server centrePlain: " + centrePlain + "\n");
                    }

        }catch (IOException | ClassNotFoundException ex) {
                  resultTxtArea.append("Authentication Error: " + ex.getMessage() + "\n");
                  ex.printStackTrace();
       }
//       finally {
//                  try {
//                      socket.close();
//                  } catch (IOException e) {
//                      e.printStackTrace();
//                  }
//              }

    }//GEN-LAST:event_authButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public class UploadListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            int taskIndex = taskListCombobox.getSelectedIndex();
            String fileName = classFiles[taskIndex];

            if (!uploaded[taskIndex]) {
                uploaded[taskIndex] = true;
                resultTxtArea.append("Uploading " + fileName + " is done.\n");

            } else {
                resultTxtArea.append(fileName + " has been uploaded already!\n");
            }
        }
    }



    public class OffloadTaskListener implements ActionListener {

        public void actionPerformed(ActionEvent e) {

            offloadTask();
        }

    }

    // Offload Task method to send Task Object to server and Receive the Object back from server
    public void offloadTask() {
        if (sessionKey == null) {
            resultTxtArea.append("Error: Session key is null. Authentication may have failed. Please authenticate first.\n");
            return;
        }

        int taskIndex = taskListCombobox.getSelectedIndex();
        String fileName = classFiles[taskIndex];

        if (uploaded[taskIndex]) {
            try {
                if (socket == null || socket.isClosed() || !socket.isConnected()) {
                    resultTxtArea.append("Socket is closed or not connected. Please reconnect.\n");
                    setConnection();
                    return;
                }
                
                String inputMessage = getDialogMessage(taskIndex);
                String input = JOptionPane.showInputDialog(this, inputMessage);

                if (input != null) {
                    Task userTask = createTask(taskIndex, input);
                    Object  encryptTask =   SecurityUtil.SymEncrypt(SecurityUtil.convertObjectToBytes(userTask), sessionKey);
                    out.writeObject(encryptTask);
                    out.flush();
                    
                    // Receive and decrypt the result
                    Object encryptedResult = in.readObject();
                    Object result = null;
                    
                    if (encryptedResult instanceof String) {
                        result = SecurityUtil.SymDecryptObj((String)encryptedResult, sessionKey);
                    } else {
                        result = encryptedResult;
                    }
                    
                    if (result instanceof Task) {
                        Task taskResult = (Task) result;
                        Object taskOutput = taskResult.getResult();
                        if (taskOutput != null) {
                            resultTxtArea.append(taskOutput.toString());
                        }
                        resultTxtArea.append("-----------------------------------\n");
                    } else if (result != null) {
                        resultTxtArea.append(result.toString());
                        resultTxtArea.append("-----------------------------------\n");
                    }
                }
            } catch (IOException | ClassNotFoundException e) {
                resultTxtArea.append("Error during task offload: " + e.getMessage() + "\n");
                e.printStackTrace();
            }
        } else {
            resultTxtArea.append("Please upload the class file for this task " + fileName + "! \n");
        }
    }

    // Initiate task
    private Task createTask(int taskIndex, String input) {
        switch (taskIndex) {
            case 0:
                return new Fibonacci(Integer.parseInt(input));
            case 1:
                return new PerfectNumber(Integer.parseInt(input));
            case 2:
                return new Factorization(Long.parseLong(input));
            default:
                return null;
        }
       
    }

    private String getDialogMessage(int taskIndex) {
     switch (taskIndex) {
            case 0:
                return "Number of sequence items: ";
            case 1:
                return "Perfect numbers up to: ";
            case 2:
                return "The number to factorise: ";
        }
         return null;
    }
 
    public String getUserName(){
        return userNameTF.getText();
    }





    public JComboBox<String> getTaskListComboBox() {
        return taskListCombobox;
    }

    public String getSelectedTask() {
        return (String) taskListCombobox.getSelectedItem();
    }

    // Close socket method
    private void  closeSocket(){

        try {
            if (socket != null && !socket.isClosed()) {
                socket.close();
            }
        } catch (IOException e) {
            System.out.println("Error closing socket: " + e.getMessage());
        }
    }


    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField hostTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton offloadButton;
    private javax.swing.JTextField portTxt;
    private javax.swing.JTextArea resultTxtArea;
    private javax.swing.JButton setButton;
    private javax.swing.JComboBox<String> taskListCombobox;
    private javax.swing.JButton uploadButton;
    private javax.swing.JTextField userNameTF;
    // End of variables declaration//GEN-END:variables
}

